### ISSUE TITLE
AP0 Konzeption

### ISSUE THREAD

**Issue by ghost** [tuwien-geoweb-2015/g01-project#1]
Ideenfindung für die Projektidee und Umsetzung.
Teambuilding, Aufgabenverteilung, Organisation,...

**Comment by ahocevar** [comment]
Ergebnisse wo?

**Comment by ghost** [comment]
- Teambuilding hat ja in der LVA stattgefunden
- Aufgabenverteilung intern abgesprochen
- Ideenfindung für die Projektidee siehe Disposition (README.md)
