### ISSUE TITLE
AP1 Grundstrukturierung

### ISSUE THREAD

**Issue by ghost** [tuwien-geoweb-2015/g01-project#2]
Aufbau der grundlegenden Projektstruktur, Entwurf der Projekthomepage,...

Disposition hochladen

**Comment by ghost** [comment]
Lieber @ahocevar ,

wir wollten gerade mit unserer Projektarbeit anfangen und haben dabei bemerkt, dass der Themenschwerpunkt, den wir uns zu Beginn der LVA überlegt haben, bereits in den vergangenen  Jahren bearbeitet wurde.

Stellt das ein Problem dar, oder sollen/können wir beim Thema (City Bike Standorte) bleiben?

**Comment by ahocevar** [comment]
Das ist kein Problem. Ihr solltet halt im Endeffekt eine Applikation haben, die sich erkennbar von anderen unterscheidet.

**Comment by ahocevar** [comment]
Ticket bitte erst schließen, wenn die Schritte erledigt sind. Also z.B. Link zur Disposition.

**Comment by ghost** [comment]
Disposition ist nun im Repository / README.md enthalten!
