### ISSUE TITLE
AP2 Datenbeschaffung und Dateneinbindung

### ISSUE THREAD

**Issue by ghost** [tuwien-geoweb-2015/g01-project#3]
1) Beschaffung der OGD Daten (City Bike, Carsharing, U-Bahn, Straßenbahn, Bus, ...)
2) Einbinden der Daten in die SpatiaLite Datenbank
3) Publizieren über den Geoserver

**Comment by ghost** [comment]
@ahocevar wir haben nun mit der eigentlichen Entwicklung der Applikation begonnen.
Leider sind uns schon ein paar Probleme untergekommen:
- Das .shp-File für die Bezirksgrenzen Wiens haben wir nicht in die SpatiaLite Datenbank (über SpatiaLite GUI) importieren können, weil wir die SRID nicht wissen und beim hineinladen ein Fehler (load shp error: Invalid character sequence)
- Die Daten für die Citybike Stationen sind in Geoserver scheinbar nicht als Punktdaten reingeladen, sondern als seltsamer Typ (siehe Bild)
  <img width="21" alt="bildschirmfoto 2015-12-01 um 13 34 47" src="https://cloud.githubusercontent.com/assets/15377565/11500900/6af37842-9830-11e5-8e0c-739a52b4eca1.png">
- Generell fehlt uns etwas die Vorgehensweise, könnten sie vielleicht noch das Beispiel aus der letzten Einheit hochladen?

Danke und liebe Grüße,
g01

**Comment by ahocevar** [comment]
> Das .shp-File für die Bezirksgrenzen Wiens haben wir nicht in die SpatiaLite Datenbank (über SpatiaLite GUI) importieren können, weil wir die SRID nicht wissen und beim hineinladen ein Fehler (load shp error: Invalid character sequence)

Die SRID findet man entweder direkt in der dem Shapefile beiliegenden .prj Datei, oder durch Hochladen der .prj Datei auf http://prj2epsg.org. Wichtig ist auch, dass das Encoding stimmt (sollte UTF-8 sein).

> Die Daten für die Citybike Stationen sind in Geoserver scheinbar nicht als Punktdaten reingeladen, sondern als seltsamer Typ (siehe Bild)

Habt ihr das auch vom Shapefile importiert? Da ist wohl etwas gröber schiefgelaufen. Dokumentiert einmal die Schritte, die ihr versucht habt, um diese Punkte in die Datenbank bzw. in GeoServer zu bekommen.

> Generell fehlt uns etwas die Vorgehensweise, könnten sie vielleicht noch das Beispiel aus der letzten Einheit hochladen?

Ist verfügbar unter http://student.ifip.tuwien.ac.at/geoweb/2015/ifip/block6/, und als solches auch über SFTP am Studentenwebspace.

**Comment by ghost** [comment]
Bei den Citybike-Stationen haben wir das CSV-File in SpatiaLite geladen (Files / Advanced / Load CSV/TXT). Danach eben die Datenbank auf den Studentenwebspace geladen und in Geoserver einen neuen Datenspeicher angelegt (heißt mobilitaetsstandortanalyse). Dann eben den Layer der Citybike-Daten publiziert und das erwähnte Ergebnis bekommen. 
Ist das Problem wahrscheinlich, dass wir garkein Shapefile geladen haben, sondern nur das CSV-File?

**Comment by ahocevar** [comment]
Richtig, das ist das Problem. Im CSV ist keine (geeignete) Geometrie für SpatiaLite/GeoServer.

**Comment by ghost** [comment]
<img width="509" alt="bildschirmfoto 2015-12-03 um 10 54 26" src="https://cloud.githubusercontent.com/assets/15377565/11557299/499a71b4-99ac-11e5-947c-40c24d390fc3.png">

SRID sollte also 4326 sein, wenn wir ein Shape (egal ob Bezirksgrenzen, Citybike-Stationen oder Carsharing-Stationen) kommt trotzdem folgender Fehler:

<img width="424" alt="bildschirmfoto 2015-12-03 um 10 51 51" src="https://cloud.githubusercontent.com/assets/15377565/11557302/4ccad89c-99ac-11e5-9f78-a354c801f0c0.png">

**Comment by ghost** [comment]
Wir haben die Shapes jetzt als "Virtual Shapefile" in SpatiaLite GUI geladen, das hat immerhin funktioniert. Passt das auch?

**Comment by ahocevar** [comment]
Virtual Shapefile ist nicht gut. Davon rate ich stark ab. Das bereitet im weiteren Verlauf Probleme.

Wie ich ja in der Vorlesung gesagt habe, sind Shapefiles bei uns meist UTF-8 oder ISO-8859-1. Ich habe gerade die Bezirksgrenzen probiert, und die sind ISO-8859-1. Die anderen werden dann wohl auch so sein.

**Comment by ghost** [comment]
Okay durch den Wechsel auf ISO-8859-1 hat das Reinladen jetzt funktioniert, es wir aber in GeoServer wieder dieses Symbol angezeigt ![vector](https://cloud.githubusercontent.com/assets/15377565/11561401/8a89ea7c-99c7-11e5-8075-a29c4e27fc0c.png) und kein ![bullet_blue](https://cloud.githubusercontent.com/assets/15377565/11561413/97ce29be-99c7-11e5-90f2-9da4e98f7868.png) oder ![shape_square_blue](https://cloud.githubusercontent.com/assets/15377565/11561414/97d037e0-99c7-11e5-9dc3-5bb0349322db.png)

**Comment by ahocevar** [comment]
Klickt mal in der Layer-Konfiguration ganz unten auf "Reload feature type". Dann sollte es passen.

Eine Sache noch, die mir bei beiden Layern auffällt: es ist wichtig, dass die Geometrie-Spalte 'geom' heißt, und nicht wie bei euch 'Geometry'. Am besten beide Shapefiles noch einmal neu importieren. Dann genügt es auch wieder, im GeoServer bei der Layer-Konfiguration "Reload feature type" zu sagen.

**Comment by ghost** [comment]
Danke, hat super funktioniert, hängen aber leider gleich wieder:

Wenn wir in unserer .sqlite-Datei Änderungen vornehmen (z.B. Bevölkerungsdaten neu hineinladen), werden diese dann in GeoServer automatisch übernommen oder müssen wir alles neu hineinladen/publizieren?

**Comment by ahocevar** [comment]
Einfach die Datei ändern, wieder hochladen, und dann nur kurz im GeoServer in die Datenspeicher-Konfiguration und dort "Speichern" sagen. Damit wird alles neu eingelesen.

**Comment by ghost** [comment]
Passt!

Wir haben jetzt unser Bezirksgrenzen-Shape mit den Bevölkerungsdaten gejoined (etwa wie g04 hier https://github.com/tuwien-geoweb-2015/g04_ue/issues/6), wissen aber gerade garnicht mehr wie und was wir mit diesen DataDict.txt und DataSet.txt Dateien anfangen sollen, damit man die Auswahl im Dropdown-Menü auf der Homepage hat und die Daten entsprechend auch in der Karte angezeigt werden.

Unser derzeitiger Arbeitsstand ist übrigens auch online unter http://student.ifip.tuwien.ac.at/geoweb/2015/g01/project/ einsehbar!
Nächster Schritt wäre dann wahrscheinlich, den angezeigten Punktdaten Symbolen zu geben.

**Comment by ahocevar** [comment]
> wissen aber gerade garnicht mehr wie und was wir mit diesen DataDict.txt und DataSet.txt Dateien anfangen sollen, damit man die Auswahl im Dropdown-Menü auf der Homepage hat und die Daten entsprechend auch in der Karte angezeigt werden.

Die `DataSet.txt` Datei werdet ihr gar nicht mehr brauchen, when ihr die Bevölkerungsdaten schon in der Datenbank habt. Die `DataDict.txt` Datei solltet ihr aktualisieren, sodass sie eure Attributfeldnamen von den Bevölkerungsdaten und zu jedem Feld eine Beschreibung enthält.

**Comment by ghost** [comment]
Gibt es die Infos irgendwo "fertig" zum verwenden für diese DataDict.txt?
Wir haben es gerade versucht "händisch" zu schreiben, dann siehts aber leider so aus:

<img width="1270" alt="bildschirmfoto 2015-12-09 um 19 39 04" src="https://cloud.githubusercontent.com/assets/15377565/11694848/8ac24036-9eac-11e5-8354-0e20b4b7a1f7.png">

**Comment by ghost** [comment]
Anzeige funktioniert schon!

**Comment by ahocevar** [comment]
Die Spaltenanordnung muss gleich sein wie im Original. Aber das habt ihr wahrscheinlich eh schon rausgefunden.

**Comment by ghost** [comment]
Ja wir haben den Teil in der .js Datei etwas umgeschrieben, damit die DataDict.txt richtig eingelesen wird... das geht wohl auch so!

**Comment by ahocevar** [comment]
Sehr fein!

**Comment by ghost** [comment]
Datenbeschaffung und Einbindung erfolgreich abgeschlossen. Ergebnis siehe GeoServer / Studenten-Webspace.
