### ISSUE TITLE
AP3 App-Entwicklung und UI-Gestaltung

### ISSUE THREAD

**Issue by ghost** [tuwien-geoweb-2015/g01-project#4]
1) Daten aus der Geo-Datenbank in die Applikation einbinden
2) Visualisierung (z.B. Gestaltung der Icons/Marker)

**Comment by ghost** [comment]
Team-interne Erinnerung: Icons von punktförmigen Daten müssen in GeoServer über Stil Editor erstellt werden. Dazu muss ein (xml?) Code geschrieben werden, siehe Beispiele.

**Comment by ghost** [comment]
Guten Morgen Herr @ahocevar 

EDIT

Haben das Problem mit der Anzeige der Punktdaten wieder irgendwie gelöst ;) siehe http://student.ifip.tuwien.ac.at/geoweb/2015/g01/project/

Können Sie uns nur noch sagen, wo und wie wir jetzt noch genau weitermachen können?

**Comment by Buglkrax** [comment]
Haben das Problem wieder irgendwie gelöst ;) siehe http://student.ifip.tuwien.ac.at/geoweb/2015/g01/project/

Können Sie uns nur noch sagen, wo und wie wir jetzt noch genau weitermachen können?

**Comment by ahocevar** [comment]
Als erstes fällt mir auf, dass die Datei http://student.ifip.tuwien.ac.at/geoweb/2015/g01/project/DataDict.txt nicht existiert. Daher werden keine Layer zur Auswahl angezeigt. Und das nächste ist, dass die Punkte in der Karte zwar nett sind, aber es viel netter wäre, wenn Infos zu den Punkten auch beim Klick auf einen Punkt angezeigt würden. Und eine Legende für die Punkte wäre auch noch wichtig. Dann fällt mir auch noch auf, dass die Kommentare noch nicht funktionieren.

**Comment by ghost** [comment]
Die DataDict.txt haben wir wahrscheinlich gerade erst reingeladen, sie sollte nämlich schon am Server liegen.

**Comment by ghost** [comment]
Wir haben uns jetzt gleich an die Kommentarfunktion gemacht, also der sqlite-Datenbank ein Comment-Table hinzugefügt (wie in ihren Folien gezeigt), jedoch ist diese nicht als Layer in GeoServer auffindbar. Wir haben schon versucht neu zu laden usw.

**Comment by ghost** [comment]
Nochmal zu der DataDict.txt:
Wir haben sie auf den Studenten-Webspace geladen, es kann aber scheinbar irgendwie nicht darauf zugegriffen werden. Beim lokalen Testen funktioniert es aber. Woran könnte das liegen?

**Comment by ahocevar** [comment]
Eventuell habt ihr falsche Rechte auf die Datei gesetzt. Sie soll von owner und group zumindest lesbar sein.

**Comment by ghost** [comment]
Ahja super, das wars anscheinend. Sollte funktionieren!
