### ISSUE TITLE
AP5 Open Beta Phase

### ISSUE THREAD

**Issue by ghost** [tuwien-geoweb-2015/g01-project#6]
1) vorläufiger Release der App ("Open Beta")
2) grundlegender Check durch Betreuer
3) Bug-Fixing und Einarbeiten von Kritik bzw. Änderungsvorschlägen

**Comment by ghost** [comment]
Lieber Herr @ahocevar, könnten Sie sich unsere Applikation ansehen und sagen, ob das so abgabefähig ist? :computer: 

Abrufbar unter: http://student.ifip.tuwien.ac.at/geoweb/2015/g01/project/

**Comment by ahocevar** [comment]
Schaut nicht schlecht aus, aber die abgegebenen Kommentare werden nicht angezeigt.
